// js/reports.js — BuildTrack Weekly Site Report Generator
// ─────────────────────────────────────────────────────────────
// Ported from MERN Reports.js — generates a structured weekly
// site report entirely from local Firestore data (no AI/API call).
// Called from dashboard-patch.js when the Reports section opens.
// ─────────────────────────────────────────────────────────────

import { db } from "./firebase.js";
import {
  collection, getDocs, query, where, orderBy, limit
} from "https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore.js";

// ── Helpers ───────────────────────────────────────────────────
const fmt = n => "₹" + Number(n || 0).toLocaleString("en-IN");

function userCol(uid, name) {
  return collection(db, "users", uid, name);
}

// ── Build the plain-text report string (ported 1:1 from MERN) ─
function generateReportText({
  startStr, weekEnd, projFilter,
  logs, labourers, att, expenses, issues,
  present, totalAtt, pct, labourCost, totalExp
}) {
  const catTotals = {};
  expenses.forEach(e => {
    catTotals[e.category] = (catTotals[e.category] || 0) + (e.amount || 0);
  });
  const catLines = Object.entries(catTotals)
    .map(([cat, amt]) => `   • ${cat}: ${fmt(amt)}`)
    .join("\n");

  const topWorkers = labourers.slice(0, 5).map(l => {
    const labId = l.id || l._id || "";
    const days = att.filter(a => a.labourerId === labId && a.status === "present").length;
    return `   • ${l.name} (${l.role || "Worker"}) — ${days} days present`;
  }).join("\n");

  const issueLines = issues.slice(0, 5)
    .map(i => `   • [${(i.severity || "medium").toUpperCase()}] ${i.title} — ${i.projectName || i.project || "General"}`)
    .join("\n") || "   • No open issues.";

  const logLines = logs.slice(0, 5)
    .map(l => `   • [${l.date}] ${l.project || "General"}: ${l.description}`)
    .join("\n") || "   • No journal entries this week.";

  const absent = totalAtt - present;
  const genDate = new Date().toLocaleDateString("en-IN", {
    day: "numeric", month: "long", year: "numeric"
  });

  return `════════════════════════════════════════════════
BUILDTRACK — WEEKLY SITE REPORT
════════════════════════════════════════════════
Period      : ${startStr} to ${weekEnd}
Project     : ${projFilter || "All Projects"}
Generated   : ${genDate}
════════════════════════════════════════════════

1. WEEKLY SUMMARY
─────────────────
This report covers site activity for the week ending ${weekEnd}.
A total of ${logs.length} journal ${logs.length === 1 ? "entry was" : "entries were"} recorded across active projects.
Labour attendance stood at ${pct}% with ${present} workers present out of ${totalAtt} recorded.
Total weekly expenditure amounts to ${fmt(totalExp)}, including labour costs of ${fmt(labourCost)}.
${issues.length > 0
  ? `There ${issues.length === 1 ? "is" : "are"} currently ${issues.length} open site ${issues.length === 1 ? "issue" : "issues"} requiring attention.`
  : "No open site issues this week."}

2. WORK PROGRESS
─────────────────
${logLines}
${logs.length > 5 ? `   ... and ${logs.length - 5} more entries.` : ""}

3. LABOUR & ATTENDANCE
───────────────────────
Total Records    : ${totalAtt}
Present          : ${present} (${pct}%)
Absent           : ${absent}
Total Labour Cost: ${fmt(labourCost)}

Top Workers This Week:
${topWorkers || "   • No worker data available."}

4. FINANCIAL SNAPSHOT
──────────────────────
Total Weekly Spend : ${fmt(totalExp)}
Labour Cost        : ${fmt(labourCost)}
Other Expenses     : ${fmt(Math.max(0, totalExp - labourCost))}

Breakdown by Category:
${catLines || "   • No expenses recorded this week."}

5. ISSUES & RECOMMENDATIONS
─────────────────────────────
Open Issues (${issues.length}):
${issueLines}

Recommendations:
${pct < 70
  ? "   ⚠ Attendance is below 70% — investigate absenteeism and ensure adequate staffing.\n"
  : "   ✓ Attendance is satisfactory.\n"}${issues.filter(i => i.severity === "high").length > 0
  ? `   ⚠ ${issues.filter(i => i.severity === "high").length} high-severity ${issues.filter(i => i.severity === "high").length === 1 ? "issue requires" : "issues require"} immediate attention.\n`
  : "   ✓ No high-severity issues open.\n"}${logs.length === 0
  ? "   ⚠ No journal entries this week — ensure site supervisors log daily progress.\n"
  : "   ✓ Site journal entries are up to date.\n"}
ACTION PLAN FOR NEXT WEEK:
   → Maintain attendance above 80%
   → Resolve all open high-severity issues
   → Ensure daily journal entries are posted
   → Review material stock levels

════════════════════════════════════════════════
Report generated by BuildTrack Report System
════════════════════════════════════════════════`;
}

// ── Fetch all needed data from Firestore ──────────────────────
async function gatherData(uid, projFilter, weekEnd) {
  const endDate   = new Date(weekEnd);
  const startDate = new Date(endDate);
  startDate.setDate(endDate.getDate() - 6);
  const startStr = startDate.toISOString().split("T")[0];

  setStep("Fetching attendance records…");
  const attSnap = await getDocs(query(
    userCol(uid, "attendance"),
    where("date", ">=", startStr),
    where("date", "<=", weekEnd)
  ));
  const att = attSnap.docs.map(d => d.data());

  setStep("Gathering labourer data…");
  const labSnap = await getDocs(userCol(uid, "labourers"));
  const labourers = labSnap.docs.map(d => ({ id: d.id, ...d.data() }));

  setStep("Loading site journal…");
  const logsSnap = await getDocs(query(
    userCol(uid, "daily_logs"),
    where("date", ">=", startStr),
    where("date", "<=", weekEnd)
  ));
  const logs = logsSnap.docs.map(d => d.data())
    .filter(l => !projFilter || l.project === projFilter);

  setStep("Loading expenses…");
  const expSnap = await getDocs(query(
    userCol(uid, "expenses"),
    where("date", ">=", startStr),
    where("date", "<=", weekEnd)
  ));
  const expenses = expSnap.docs.map(d => d.data())
    .filter(e => !projFilter || e.projectName === projFilter || e.project === projFilter);

  setStep("Loading open issues…");
  const issSnap = await getDocs(query(
    userCol(uid, "issues"),
    where("status", "==", "open")
  ));
  const issues = issSnap.docs.map(d => d.data());

  // Compute stats
  const present    = att.filter(a => a.status === "present").length;
  const totalAtt   = att.length;
  const labourCost = labourers.reduce((s, l) => {
    const days = att.filter(a => a.labourerId === l.id && a.status === "present").length;
    return s + days * (l.wagePerDay || 0);
  }, 0);
  const totalExp = expenses.reduce((s, e) => s + (e.amount || 0), 0);
  const pct      = totalAtt ? Math.round(present / totalAtt * 100) : 0;

  return {
    startStr, weekEnd, projFilter,
    logs, labourers, att, expenses, issues,
    present, totalAtt, pct, labourCost, totalExp
  };
}

// ── Inject the Report Generator UI into the reports section ───
export function injectWeeklyReportUI() {
  const section = document.getElementById("reports");
  if (!section || document.getElementById("weeklyReportPanel")) return;

  const panel = document.createElement("div");
  panel.id = "weeklyReportPanel";
  panel.style.marginBottom = "28px";

  panel.innerHTML = `
    <div class="weekly-report-card">

      <!-- Header -->
      <div class="wr-header">
        <div class="ai-badge" style="margin-bottom:12px;">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M18 20V10M12 20V4M6 20v-6"/></svg>
          Weekly Report
        </div>
        <div class="wr-title">Weekly Site Report Generator</div>
        <div class="wr-subtitle">Analyses your last 7 days of site data and generates a full contractor report instantly.</div>
      </div>

      <!-- Stats row (shown after generation) -->
      <div id="wrStatsRow" style="display:none;" class="wr-stats-row">
        <div class="stat-card"><div class="stat-label">Attendance</div><div class="stat-value green" id="wrStatAtt">—</div></div>
        <div class="stat-card gold"><div class="stat-label">Labour Cost</div><div class="stat-value gold" id="wrStatLabour">—</div></div>
        <div class="stat-card"><div class="stat-label">Weekly Spend</div><div class="stat-value" id="wrStatSpend">—</div></div>
        <div class="stat-card"><div class="stat-label">Open Issues</div><div class="stat-value" id="wrStatIssues">—</div></div>
      </div>

      <!-- Controls -->
      <div class="wr-controls">
        <div class="wr-control-row">
          <div class="field-group" style="flex:1;min-width:160px;">
            <label class="field-label">Project</label>
            <select id="wrProjectSelect" class="field-input">
              <option value="">All Projects</option>
            </select>
          </div>
          <div class="field-group" style="flex:1;min-width:160px;">
            <label class="field-label">Week ending</label>
            <input type="date" id="wrWeekEnd" class="field-input">
          </div>
        </div>
        <button class="ai-generate-btn" id="wrGenerateBtn" onclick="window.generateWeeklyReport()">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M18 20V10M12 20V4M6 20v-6"/></svg>
          Generate Weekly Report
        </button>
      </div>

      <!-- Loading -->
      <div id="wrLoading" style="display:none;" class="ai-loading-box">
        <div class="ai-spinner"></div>
        <div class="ai-loading-text">Analysing site data…</div>
        <div class="ai-loading-sub" id="wrStep">Fetching records…</div>
      </div>

      <!-- Output -->
      <div id="wrOutput" style="display:none;" class="wr-output-box">
        <div class="ai-output-toolbar">
          <span class="ai-output-label">
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14,2 14,8 20,8"/></svg>
            Generated Report
          </span>
          <div style="display:flex;gap:8px;">
            <button class="btn btn-sm btn-secondary" onclick="window.copyWeeklyReport()">Copy</button>
            <button class="btn btn-sm btn-secondary" onclick="window.downloadWeeklyReport()">
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
              Download .txt
            </button>
          </div>
        </div>
        <div id="wrContent" class="wr-content"></div>
      </div>

    </div>

    <style>
      .weekly-report-card {
        background: var(--surface-2, #1C1C1F);
        border: 1px solid rgba(245,166,35,0.2);
        border-radius: 20px;
        overflow: hidden;
      }
      .wr-header { padding: 28px 28px 0; margin-bottom: 20px; }
      .wr-title {
        font-family: 'Bebas Neue', sans-serif;
        font-size: 1.8rem; letter-spacing: 1px;
        color: var(--text, #F0EDE8); margin-bottom: 6px;
      }
      .wr-subtitle { color: var(--text-muted, #7A7872); font-size: 0.85rem; }
      .wr-stats-row {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 14px;
        padding: 0 28px 20px;
      }
      .wr-controls { padding: 0 28px 24px; }
      .wr-control-row { display: flex; gap: 14px; margin-bottom: 14px; flex-wrap: wrap; }
      .wr-output-box { border-top: 1px solid rgba(255,255,255,0.05); }
      .wr-content {
        padding: 28px;
        background: var(--surface-3, #141416);
        font-family: monospace;
        font-size: 0.85rem;
        line-height: 1.9;
        color: var(--text-2, #A09D99);
        white-space: pre-wrap;
        max-height: 600px;
        overflow-y: auto;
      }
      @media (max-width: 600px) {
        .wr-stats-row { grid-template-columns: repeat(2, 1fr); }
        .wr-control-row { flex-direction: column; }
        .wr-header, .wr-controls { padding-left: 18px; padding-right: 18px; }
        .wr-content { padding: 18px; }
      }
    </style>
  `;

  // Insert at the top of the reports section, before existing stat cards
  const firstChild = section.querySelector(".section-header");
  if (firstChild?.nextSibling) {
    section.insertBefore(panel, firstChild.nextSibling);
  } else {
    section.appendChild(panel);
  }

  // Set default date
  const dateEl = document.getElementById("wrWeekEnd");
  if (dateEl) dateEl.value = new Date().toISOString().split("T")[0];
}

// ── Populate project dropdown ──────────────────────────────────
export function populateWeeklyReportProjects(projects) {
  const sel = document.getElementById("wrProjectSelect");
  if (!sel) return;
  sel.innerHTML = `<option value="">All Projects</option>`;
  projects.forEach(p => {
    sel.innerHTML += `<option value="${p.name}">${p.name}</option>`;
  });
}

// ── Main generate function (global so HTML onclick can call it) ─
window.generateWeeklyReport = async function() {
  const uid = window._uid || window._buildtrackUID;
  if (!uid) return alert("Please log in first.");

  const projFilter = document.getElementById("wrProjectSelect")?.value || "";
  const weekEnd    = document.getElementById("wrWeekEnd")?.value || new Date().toISOString().split("T")[0];

  // Show loading, hide old output
  document.getElementById("wrOutput").style.display = "none";
  document.getElementById("wrStatsRow").style.display = "none";
  document.getElementById("wrLoading").style.display = "flex";
  document.getElementById("wrGenerateBtn").disabled = true;

  try {
    const data = await gatherData(uid, projFilter, weekEnd);

    // Update stats row
    document.getElementById("wrStatAtt").textContent    = data.pct + "%";
    document.getElementById("wrStatLabour").textContent = fmt(data.labourCost);
    document.getElementById("wrStatSpend").textContent  = fmt(data.totalExp);
    document.getElementById("wrStatIssues").textContent = data.issues.length;
    document.getElementById("wrStatsRow").style.display = "grid";

    // Small delay so loading state is visible (mirrors MERN 800ms pause)
    setStep("Writing your report…");
    await new Promise(r => setTimeout(r, 600));

    const text = generateReportText(data);
    window._lastWeeklyReport     = text;
    window._lastWeeklyReportDate = weekEnd;

    document.getElementById("wrContent").textContent = text;
    document.getElementById("wrLoading").style.display = "none";
    document.getElementById("wrOutput").style.display  = "block";

  } catch (err) {
    console.error("[WeeklyReport] Error:", err);
    document.getElementById("wrContent").textContent = "Error generating report: " + err.message;
    document.getElementById("wrLoading").style.display = "none";
    document.getElementById("wrOutput").style.display  = "block";
  } finally {
    document.getElementById("wrGenerateBtn").disabled = false;
  }
};

// ── Copy to clipboard ─────────────────────────────────────────
window.copyWeeklyReport = function() {
  const text = window._lastWeeklyReport || "";
  navigator.clipboard.writeText(text).then(() => {
    const btn = document.querySelector("#wrOutput .btn-secondary");
    if (btn) {
      const orig = btn.textContent;
      btn.textContent = "Copied!";
      setTimeout(() => btn.textContent = orig, 2000);
    }
  });
};

// ── Download as .txt ──────────────────────────────────────────
window.downloadWeeklyReport = function() {
  const text = window._lastWeeklyReport || "";
  const date = window._lastWeeklyReportDate || new Date().toISOString().split("T")[0];
  const blob  = new Blob([text], { type: "text/plain" });
  const url   = URL.createObjectURL(blob);
  const a     = document.createElement("a");
  a.href = url;
  a.download = `BuildTrack_Report_${date}.txt`;
  a.click();
  URL.revokeObjectURL(url);
};

// ── Loading step helper ────────────────────────────────────────
function setStep(text) {
  const el = document.getElementById("wrStep");
  if (el) el.textContent = text;
}
